AWSTemplateFormatVersion: "2010-09-09"
Description: "Brian S3 Bucket"
Parameters:
  BrianS3BucketName:
    Type: String
Resources:
  BrianS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join [ '-', [Ref: "AWS::AccountId", Ref: BrianS3BucketName] ]

